# Generated by Django 2.2.7 on 2019-11-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eresource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='publisher',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebooks', to='eresource.Publisher'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='vendor',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebooks', to='eresource.Vendor'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
